# Site settings
title: Tin Dandelion's Diary
tagline: ...growing on the silicon fields
email: info@tindandelion.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tindandelion.com" # the base hostname & protocol for your site
twitter_username: tin_dandelion
github_username:  tindandelion

exclude: ["Gemfile", "Gemfile.lock", "CNAME"]

# Build settings
markdown: kramdown
